import type { Metadata } from "next";
import { ibmPlexMono } from "@/data/fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "Branden Basche Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ibmPlexMono.className}>{children}</body>
    </html>
  );
}
